<!DOCTYPE html>
<html>
<head>
    <title>{{ $title }}</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { font-size: 24px; margin-bottom: 5px; }
        .header p { font-size: 14px; color: #666; }
        .summary { margin-bottom: 20px; }
        .summary-item { margin-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table th, table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        table th { background-color: #f2f2f2; }
        .footer { margin-top: 30px; font-size: 12px; color: #666; text-align: center; }
        .section-title { font-size: 18px; margin: 20px 0 10px 0; border-bottom: 1px solid #eee; padding-bottom: 5px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Date Range: {{ $dateRange }}</p>
        <p>Generated on: {{ now()->format('d/m/Y H:i') }}</p>
    </div>
    
    <div class="summary">
        <div class="summary-item">
            <strong>Total {{ $reportData['report_type'] == 'sales' ? 'Sales' : 'Purchases' }}:</strong> 
            {{ $reportData['transactions']->count() }}
        </div>
        <div class="summary-item">
            <strong>Total {{ $reportData['report_type'] == 'sales' ? 'Revenue' : 'Cost' }}:</strong> 
            {{ number_format($reportData['transactions']->sum(function($t) { return $t->quantity * $t->price; }), 2) }} DH
        </div>
        <div class="summary-item">
            <strong>Items {{ $reportData['report_type'] == 'sales' ? 'Sold' : 'Purchased' }}:</strong> 
            {{ $reportData['transactions']->sum('quantity') }}
        </div>
    </div>
    
    <div class="section-title">Transaction Details</div>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Reference</th>
                <th>Product</th>
                <th>{{ $reportData['report_type'] == 'sales' ? 'Client' : 'Supplier' }}</th>
                <th>Qty</th>
                <th>Unit Price</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData['transactions'] as $transaction)
            <tr>
                <td>{{ $transaction->date ? $transaction->date->format('d/m/Y') : 'N/A' }}</td>
                <td>{{ $transaction->reference ?? 'N/A' }}</td>
                <td>{{ $transaction->product->name ?? 'N/A' }}</td>
                <td>
                    @if($reportData['report_type'] == 'sales')
                        {{ $transaction->client->name ?? 'N/A' }}
                    @else
                        {{ $transaction->supplier->name ?? 'N/A' }}
                    @endif
                </td>
                <td>{{ $transaction->quantity }}</td>
                <td>{{ number_format($transaction->price, 2) }} DH</td>
                <td>{{ number_format($transaction->quantity * $transaction->price, 2) }} DH</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    @if($reportData['topProducts']->isNotEmpty())
    <div class="section-title">
        Top {{ $reportData['report_type'] == 'sales' ? 'Sold' : 'Purchased' }} Products
    </div>
    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Total Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData['topProducts'] as $product)
            <tr>
                <td>{{ $product['name'] }}</td>
                <td>{{ $product['quantity'] }}</td>
                <td>{{ number_format($product['amount'], 2) }} DH</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif
    
    <div class="footer">
        Report generated by {{ auth()->user()->name }} on {{ config('app.name') }}
    </div>
</body>
</html>